// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oixrklybagmwriafktrb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9peHJrbHliYWdtd3JpYWZrdHJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3MzMwNzQsImV4cCI6MjA2NDMwOTA3NH0.sn1I56RQ7B66hPI6L2t9FnRk3_wXZS_49Q9M9VADRLw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);